User interface
Lichapa/tic-tac-toe pull request #4
Opened 2020-12-10 14:23 UTC by Lichapa

**In this milestone, I have done the following:**

- Prompt players to enter names and store the names in Variable

- Assign a symbol to players

- Tell the player whose turn it is.

- Show the step a player will need to play the game

2020-12-10 17:51 UTC, krys2fa requested changes
## Nicely done @Lichapa 👏 
You did really great in this milestone. Your PR title and description is well-written as well. 💪 
You have a professional-looking README in place even though it is not required in this milestone. 👍 

Just a few more changes required to complete the milestone. They can be seen below:
### Status: Changes Required ♻️ 

- [ ] [OPTIONAL] The game accepts empty spaces as a player name.

Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2020-12-10 17:51 UTC, krys2fa commented on bin/main.rb
> +    while moves < 9
* [ ] [REQUIRED]  Using out-of-nowhere numbers to terminate a loop (for example, `5.times do ... end`) is a signal that something is wrong. Please use a terminating variable instead. See below for an example where `game_on` is the terminating variable:
```
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
```

2020-12-10 19:34 UTC, blackpintz requested changes
# Status: Changes Required 🤓

## Hello team 😃,

**Great job implementing the requested changes 💪. However, there are a few fixes needed as described in the comment below.**

## Happy coding 🥂 .

**PS: You can reach me on slack (Rose Wanjohi).**

2020-12-10 19:34 UTC, blackpintz commented on bin/main.rb
> +  end
You have mapped out scenarios of how the game tells which player turn it is. Also within this loop, map out the following scenarios:

- what does it look like when a player inputs an invalid move? Also, using puts/ print, indicate the message the player gets for an invalid move.

- What does it look like when the game is drawn? Also, using puts/prints, indicate the message the players receive when the game ends in a draw.

- What does it look like when the game is won? Also,  using puts/prints, indicate the message the player receives when they win a game.

2020-12-10 19:40 UTC, blackpintz requested changes
# Status: Changes Required 🤓

## Hello team 😃,

**Great job implementing the requested changes 💪. However, there are a few fixes needed as described in the comment below.**

## Happy coding 🥂 .

**PS: You can reach me on slack (Rose Wanjohi).**

2020-12-10 19:40 UTC, blackpintz commented on bin/main.rb
> +end
[Optional] You can add this inside the game loop you created in `play` method.

2020-12-10 19:40 UTC, blackpintz commented on bin/main.rb
> +  end
You have mapped out scenarios of how the game tells which player turn it is. Also within this loop, map out the following scenarios:

- what does it look like when a player inputs an invalid move? Also, using puts/ print, indicate the message the player gets for an invalid move.

- What does it look like when the game is drawn? Also, using puts/prints, indicate the message the players receive when the game ends in a draw.

- What does it look like when the game is won? Also,  using puts/prints, indicate the message the player receives when they win a game.

2020-12-11 05:43 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️ 🛑 
HELLO, @Lichapa  👋🏿  GREAT PROGRESS. I LOVE THAT YOU ADDED A README TO YOUR PROJECT. 👏🏿 HOWEVER, THERE ARE STILL SOME CHANGES THAT NEEDS TO BE DONE. KINDLY CHECK BELOW ⬇️ 

- [ ] There are some rubocop offenses, kindly fix all the rubocop offenses ⬇️ 
![Screenshot from 2020-12-11 08-31-10](https://user-images.githubusercontent.com/32361963/101867037-56f01680-3b8b-11eb-8a4c-8fd517b34e30.png)

- [ ] [REQUIRED] game tells which player turn it is (without computing who the winner is). I can see you have a method for this in your project, however, you should try and mock it a bit more. what I mean by this is you don't have to write the logic but at least your method should print something.
**hint:** Try and utilize your loop. Remember no logic is needed.

- [ ] `[REQUIRED]` game asks the player to select from available moves. Just like I have stated I can see you have a method for this, however, try and mock it a bit more, remember no logic is required but at least let your method output something. 

- [ ] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken). After every player moves, display the board.
**hint:** you can do this by calling your board method inside your loop.

- [ ] `[REQUIRED]` game informs the player if the selected move is a winning move (without computing the winning move). I can see you have the method for this, again you don't need the logic but mock your method a bit more.

**hint:** Utilize the power of puts and print.

### if you have any question, kindly reach me on slack @peterrobert

### HAPPY CODING 💻

2020-12-16 19:48 UTC, eypsrcnuygr approved these changes
## Status Approved :partying_face: :tada: 
Hello @Lichapa. Congratulations on making the requested changes. I've checked your game and satisfies the conditions that I write down below;
* [ ] game asks players for their names
* [ ] `[REQUIRED]` game tells which player turn it is 
* [ ] `[REQUIRED]` game asks the player to select from available moves
* [ ] `[REQUIRED]` game informs player if the selected move is invalid 
* [ ] `[REQUIRED]` game displays board after the player move 
* [ ] `[REQUIRED]` game informs player if the selected move is a winning move 
* [ ] `[REQUIRED]` game informs player if the selected move is a draw move 
* [ ] `[REQUIRED]` game repeats all actions for the next player's move

### Optional

- [ ]  You can write separate files for the classes that you use. In the next milestones, it'll be asked to do it like that.
- [ ] Instead of commits like add methods you can be more descriptive on your commit messages in the future.

Congratulations again. :+1: You can merge this PR and move on to the next one.
_Eyüp Sercan UYGUR_

2020-12-17 04:55 UTC, merged