Game_logic
Lichapa/tic-tac-toe pull request #6
Opened 2020-12-18 10:02 UTC by Lichapa

In this milestone, The following was done:

- create board.rb file in lib directory
- create player.rb file in lib directory
- Add player class to lib/player.rb
- Add board class to lib/board.rb
- Add require_relative to bin./main.rb for lib/player.rb and lib/board.rb

2020-12-18 10:25 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Lichapa 
Such a remarkable project you made :+1:  :tada: 
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] Please remove `puts/print` and `gets.chomp` from `board.rb` and `player.rb` and move them to  `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- [ ] Game is terminating after the draw, the game should ask after the draw if the player wants to play again.
- [ ] Game is giving the message Cat's game! on the first draw. This message is shown when the game is continuously drawing three times. You can explore [Why is a tie in Tic-Tac-Toe called a “Cat's Game?”](https://english.stackexchange.com/questions/155621/why-is-a-tie-in-tic-tac-toe-called-a-cats-game)

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-12-18 10:25 UTC, umairarshadbutt commented on lib/board.rb
> +    puts "| #{@space[6]} | #{@space[7]} | #{@space[8]} |"
Remove the puts and move into `main.rb`

2020-12-18 10:25 UTC, umairarshadbutt commented on lib/player.rb
> +    print "#{name}, It's your turn. Please make your move:"
Remove the print and move into `main.rb`

2021-01-04 12:04 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @Lichapa**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] After a player enters his name, you should till him what his token is.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-01-04 12:38 UTC, mahmoud717 approved these changes
### STATUS: APPROVED ✔️ ✔️ 

**hi @Lichapa**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

2021-01-04 12:41 UTC, merged